config/routes.rb
WeRKD::Application.routes.draw do

  devise_for :users,
    path_prefix: "users",
    path: "",
    :controllers => {
      omniauth_callbacks: "users/omniauth_callbacks",
      invitations: 'users/invitations',
    }

  resources :tags, only: [:index]
  match "/contacts/:importer/callback" => "users/omnicontacts#callback", via: :get
  namespace :users do
    resources :omnicontacts, only: [ :index, :show]
    resources :dashboards, only: [:index]
    resources :feeds, only: [:index]
    resources :profiles, only: [:index, :update]
    resources :actions, only: [:index]
    resources :connections, only: [:index] do
      get "accept"
    end
    resources :projects, only: [:new, :create, :update, :edit]
  end
  resources :users, only: [:index, :show]
  resources :projects, only: [:show]

  namespace :api do
    resources :users
  end

  devise_scope :user do
    get "/" => "home#index"
  end
  root :to => 'home#index'

  ActiveAdmin.routes(self)
end

app/controllers/home_controller.rb
class HomeController <DeviseController

  #prepend_before_filter :require_no_authentication, :only => [ :index ]

  def index
    if user_signed_in?
      redirect_to users_feeds_url and return
    end
    self.resource = User.new
    render layout: false
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_signup_login.html.erb
<div class="row">
  <section id="signup">

    <div class="text-center">

      <div id="signup-form" class="text-center">

        <header>
          <h2>Join for Free Now</h2>
        </header>

        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :class => 'form-horizontal' }) do |f| %>
          <%= devise_error_messages! %>
          <%= f.email_field :email, placeholder: "Email", class: "input-small" %>
          <%= f.password_field :password, placeholder: "Password", class: "input-small" %>
          <%= f.submit "Let's get started!", :class => 'btn btn-primary' %>
      <%end%>

        <header id="existing" class="action text-right">
          <a data-role="existing-user">Already a member?</a>
        </header>
      </div>

      <div id="signin-form" style="display:none" class="text-center">
        <header>
          <h2>Welcome back.</h2>
        </header>

        <%= form_for(User.new, html: { class: "form-inline" }, url: user_session_path) do |f| %>
          <%= f.text_field :email, placeholder: "Email", class: "input-small" %>
        <%= f.password_field :password, placeholder: "Password", class: "input-small" %>
        <%= f.submit "Sign in", :class => 'btn btn-primary' %>
      <%end%>

        <header id="new-user" class="action text-right">
          <a data-role="new-user">New to WeRKD?</a>
        </header>
      </div>

    </div>
  </section>
</div>

<div id="alternative-signup" class="row">
  <%= render partial: "users/shared/links" %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= render partial: "layouts/opengraph"%>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WeRKD <%= content_for?(:title) ? yield(:title) : "" %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="homepage">
      <%= bootstrap_flash %>
      <div class="werkd-logo ">
        <div class="text-center">
          <%= link_to root_path do %>
            <%= image_tag "logos/landingwerkdlogo.png" %>
          <% end  %>
        </div>
      </div>
      <div class="row">
        <section id="intro-video" class="text-center">

          <iframe id="intro-video-player" src="http://player.vimeo.com/video/82886509?api=1&amp;player_id=intro-video-player&amp;byline=0&amp;portrait=0&amp;title=0&amp;"
            width="720" height="405" frameborder="0"
            webkitallowfullscreen
            style="display:none"></iframe>

          <%= image_tag "homepage/firstframe.jpg", id: "play-intro-button" %>
        </section>
      </div>

      <%=render "signup_login"%>

      <section id="distinctions" class="container">
        <div class="row text-center">
          <div class="network span4">
            <%= image_tag "homepage/network.png"%>
            <h4>Network with ease</h4>
            <p>Use shared projects and skills as icebreake.
              No more awkward introductions, shameless schmoozing and empty endorsements!
            </p>
          </div>
          <div class="build span4">
            <%= image_tag "homepage/build.png"%>
            <h4>Build project archive</h4>
            <p>
              Collectively build a sharable archive of projects through the power of creative community. Credit yourself and your peers for the work you have done.
            </p>
          </div>
          <div class="know span4">
            <%= image_tag "homepage/know.png"%>
            <h4>Know your connections</h4>
            <p>Understand people through projects and skills in the right context, and connect with confidence and clarity.
            </p>
          </div>
        </div>
      </section>

    </div>
  </body>
  <script src="http://a.vimeocdn.com/js/froogaloop2.min.js"></script>
  <%= javascript_include_tag "home" %>
  <%= render "layouts/tracking" %>
</html>